### PR TITLE
Generate .gitignore file using gitignore.io

### PR DESCRIPTION
**Pull request by punkstarman**
The service available at https://gitignore.io/ makes it easy to maintain a `.gitignore` file, relying on rules for each technology that are peer-reviewed.

### CODE REVIEW

**Comment by nweldev** [comment]
Thanks for this PR. It's always nice to learn about a new DX service :smiley:

Based on your comment on Twitter, I thought you were proposing to add a new monocli command using this service.

**Comment by noelmace** [comment]
Reminds me I forgot to activate the commitlint app on this repo, as it follows [conventionnal commits](https://www.conventionalcommits.org).

Would you mind amending your commit in order to add the "build:" type? Thx

**Review by nweldev — CHANGES_REQUESTED** [review]
Reminds me I forgot to activate the commitlint app on this repo, as it follows conventionnal commits. This is now fixed.

Would you mind amending your commit in order to add the "build:" type? Thx

**Comment by punkstarman** [comment]
> Would you mind amending your commit in order to add the "build:" type? Thx

With pleasure :smile:

**Comment by nweldev** [comment]
Thx

**Review by nweldev — APPROVED** [review]
LGTM

**Pull request merged**
